package ru.prbb.arm.hr.telephony;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */

@WebServiceClient(name = "phone_callService", targetNamespace = "http://172.23.102.4/welltime/wsdl/phone_call/", wsdlLocation = "http://172.23.102.4/welltime/wsdl/phone_call.wsdl?WSDL")
public class PhoneCallService
    extends Service
{

	private final static URL PHONECALLSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ru.prbb.arm.hr.telephony.PhoneCallService.class.getResource(".");
            url = new URL(baseUrl, "http://172.23.102.4/welltime/wsdl/phone_call.wsdl?WSDL");
        } catch (MalformedURLException e) {
        }
        PHONECALLSERVICE_WSDL_LOCATION = url;
    }

    public PhoneCallService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhoneCallService() {
        super(PHONECALLSERVICE_WSDL_LOCATION, new QName("http://172.23.102.4/welltime/wsdl/phone_call/", "phone_callService"));
    }

    /**
     * 
     * @return
     *     returns PhoneCallInterface
     */
    @WebEndpoint(name = "phone_callSOAP")
    public PhoneCallInterface getPhoneCallSOAP() {
        return super.getPort(new QName("http://172.23.102.4/welltime/wsdl/phone_call/", "phone_callSOAP"), PhoneCallInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhoneCallInterface
     */
    @WebEndpoint(name = "phone_callSOAP")
    public PhoneCallInterface getPhoneCallSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://172.23.102.4/welltime/wsdl/phone_call/", "phone_callSOAP"), PhoneCallInterface.class, features);
    }

}
